### ISSUE TITLE
Summary function missing group info for pep, metab, and proData

### ISSUE THREAD

**Issue by rarichardson92** [pmartR/pmartR#101]
For pepData, summary() will return counts for each group designation, but groups don't register for other data objects. Looking at the code in the R folder, it seems like error might be due to the use of levels() for non-pepData objects (throwing a NULL) while the pepData summary uses unique() to extract grouping data? The error can be reproduced in the code below:

-------------------
```
library(pmartRdata)
data(lipid_object)
lipid_object2 <- group_designation(omicsData = lipid_object, main_effects = "Condition")
summary(lipid_object2)

data(pro_object)
pro_object2 <- group_designation(omicsData = pro_object, main_effects = "Condition")
summary(pro_object2)

data(metab_object)
metab_object2 <- group_designation(omicsData = metab_object, main_effects = "Condition")
summary(metab_object2)

data(pep_object)
peo_object2 <- group_designation(omicsData = pep_object, main_effects = "Condition")
summary(peo_object2)
```

**Comment by clabornd** [comment]
Yep, some fool changed one of them but didn't change the rest in [this commit](https://github.com/pmartR/pmartR/commit/f1f3d0cedc014925a5ae61419ab0a05573c1282b#diff-2b7a3020f44e0e465cae67a1fa25328b)

**Comment by lmbramer** [comment]
Fixed in recent pull to master
