### ISSUE TITLE
Recent cname attribute passed in imd_anova() only applies for "combined" test method 

### ISSUE THREAD

**Issue by rarichardson92** [pmartR/pmartR#103]
The recent update for the cname attribute included in "statRes" object from imd_anova() only seems to apply for "combined" test method. From looking at the imd_anova() code in the R folder, it seems like the addition was made before the last return statement and not the return statements for if test_method equals 'anova' or 'gtest'. 
The issue can reproduced with the below code:

--------------

```
library(pmartR)
library(pmartRdata)
#Transform the data
mypepData <- edata_transform(omicsData = pep_object, data_scale = "log2")

#Group the data by condition
mypepData <- group_designation(omicsData = mypepData, main_effects = c("Condition"))

#Apply the IMD ANOVA filter
imdanova_Filt <- imdanova_filter(omicsData = mypepData)
mypepData <- applyFilt(filter_object = imdanova_Filt, omicsData = mypepData, min_nonmiss_anova=2)

#Implement the IMD ANOVA method and compute all pairwise comparisons (i.e. leave the `comparisons` argument NULL)
anova_res <- imd_anova(omicsData = mypepData, test_method = 'anova')
imd_res <- imd_anova(omicsData = mypepData, test_method = 'gtest')
imd_anova_res <- imd_anova(omicsData = mypepData, test_method = 'comb', pval_adjust='bon')

attr(imd_anova_res, "cname")

imd_anova_res <- imd_anova(omicsData = mypepData, test_method = 'gtest', pval_adjust='bon')

attr(imd_anova_res, "cname")

imd_anova_res <- imd_anova(omicsData = mypepData, test_method = 'anova', pval_adjust='bon')

attr(imd_anova_res, "cname")
```

**Comment by clabornd** [comment]
Yep, good catch.  Changing:

`   return(statRes_output(imd_out,omicsData,comparisons,test_method,pval_adjust,pval_thresh))`

to the pattern for the last return statement:

`final_out <- statRes_output(imd_out,omicsData,comparisons,test_method,pval_adjust,pval_thresh)
  attr(final_out, "cnames") = attr(omicsData, "cnames")`
`return(final_out)`

works for me.

**Comment by lmbramer** [comment]
Fixed in recent pull into master
