### ISSUE TITLE
as.proData replicates

### ISSUE THREAD

**Issue by Skourtis** [pmartR/pmartR#126]
as.proData requires replicates to be technical replicates. Does it make a difference for the analysis if my three replicates are biological replicates?

**Comment by lmbramer** [comment]
The replicates mechanism is intended to be used to average or combine technical replicates or samples that in an ideal world would generate exactly the same data/relative abundances. Biological replicates are typically leveraged as individual samples representing a "group/condition" in a statistical analysis and that group membership should be specified in your f_data and then using "group_designation" if it is part of your desired statistical analyses.
