### ISSUE TITLE
imdanova_Filt & imd_test

### ISSUE THREAD

**Issue by Skourtis** [pmartR/pmartR#128]
Hi, 

I am comparing a list of proteins for 2 conditions (each with 3 biological replicates) and I am trying to qualitatively identify proteins which are present in all 3 samples for one conditions but absent from all 3 replicates in the second condition ( NA NA NA vs Present Present Present).  However the imdanova_Filt  removes these entries and I was wondering why since this is exactly what I am looking to compare. Also when I run imd_test without filtering, I receive significant p-values for these proteins, but all the p-values are the same. Shouldn't it be based on each distribution of present proteins somehow as well, not just presence or absence?

**Comment by lmbramer** [comment]
When you use `applyFilt()` with `imdanova_filter()`, there are two parameters which can be specificed `min_nonmiss_anova` and `min_nonmiss_gtest`. If you want to quantitative tests only then you should specify the former and qualitative tests only then specify the latter, or if you wish to run both then you must specify both to avoid over-filtering the data. Setting `min_nonmiss_gtest = 3` should fix your issue.

The same p-values occuring for proteins with 3 vs 0 (present vs absent) is expected. Traditionally, the G-test conducted on proteomics data only accounts for patterns of presence/absence. See the paper 

- Webb-Robertson, B. J. M., McCue, L. A., Waters, K. M., Matzke, M. M., Jacobs, J. M., Metz, T. O., ... & Pounds, J. G. (2010). Combined statistical analyses of peptide intensities and peptide occurrences improves identification of significant peptides from MS-based proteomics data. Journal of proteome research, 9(11), 5748-5756

as an example. If there are other implementations that are desired, feel free to point us to relevant literature.

**Comment by lmbramer** [comment]
Done
