### ISSUE TITLE
Request for small helper_fn changes - Error vs. Null

### ISSUE THREAD

**Issue by rarichardson92** [pmartR/pmartR#138]
A few helper functions return errors in certain conditions where the attribute fetched does not exist for various reasons; it might be more helpful if these returned NULL with a warning? Specifically thinking about generic workflows applied across different datasets, where it can check for the attribute but catch null values in an if() statement. A few I've run into:

get_emeta_cname - errors where emeta does not exist
get_filters - errors when no filters have been applied

(Group info helpers also error if group designation hasn't been run, but I feel that is reasonable)

**Comment by evanamartin** [comment]
This issue has been addressed with pmartR version 2.0.4
