### ISSUE TITLE
pmartR v0.10.0 imd_test issue

### ISSUE THREAD

**Issue by fp215** [pmartR/pmartR#169]
Hi, having recently updated pmartR to v0.10.0, a colleague is having trouble running "imd_test" as the function appears to be missing. He had no trouble at all running exactly the same thing previously with v0.9.0.

Also, my quick fix was to suggest he revert to the older version of the software, but we couldn't find an archive version?

Thanks for your help, details below.

Input (where "p.norm" is a pepData dataset):

`test <- data.frame(Control="Control",Test="Disease")`
`imd.res <- imd_test(p.norm, comparisons=test, pal_adjust="holm", pval_thresh=0.05)`

Error message:

`Error in imd_test(p.norm, comparisons = test, pval_adjust "holm", pval_thresh = 0.05) :`
`could not find function "imd_test"`

Session info:

R version 4.1.2 (2021-11-01)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.1
Matrix products: default
BLAS:
/Library/Frameworks/R. framework/Versions/4.1/Resources/lib/libRblas.o.dylib
LAPACK:/Library/Frameworks/.framework/Versions/4.1/Resources/lib/libRlapack.dylib
locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8
attached base packages:
[1] splines
stats
graphics grDevices utils
datasets methods
base
other attached packages:
[1] missForest_1.4
[6] gridExtra_2.3
[11] limma_3.50.0
[167 usethis_2.1.5
itertools 0.1-3
ggplotz_3.3.5
reshape_0.8.8
iterators 1.0.14
WGCNA_1.70-3
plyr_1.8.6
foreach 1.5.2
fastcluster_1.2.3
pmartR_0.10.0
loaded via a namespace (and not attached):
[1] bitops_1.0-7
matrixStats_0.61.0
[6] RColorBrewer_1.1-2
httr-1.4.2
[11] tools_4.1.2
utf8 1.2.2
[16] DBI_1.1.2
BiocGenerics 0.40.0
[211 tidyselect_1.1.1
prettyunits_1.1.1
[26] compiler_4.1.2
cli_3.2.0
[317 checkmate_2.0.0
scales_1.1.1
[36] foreign_0.8-82
XVector_0.32.0
[41] pkgconfig_2.0.3
sessioninfo_1.2.2
[467 impute_1.66.0
rstudioapi_0.13
[51] RCurl_1.98-1.6
magrittr_2.0.2
[56] Matrix_1.4-0
Rcpp_1.0.8
[61] lifecycle_1.0.1
stringi_1.7.6
[667 grid_4.1.2
blob 1.2.2
[71] Biostrings_2.60.2
KEGGREST_1.32.0
[76] codetools_0.2-18
stats4_4.1.
[81] data. table_1.14.2
remotes_2.4.2
[86] qtable_0.3.0
purrr_0.3.4
[917 tibble 3.1.6
AnnotationDbi_1.54.1
[96] ellipsis_0.3.2
fs_1.5.2
rprojroot_2.0.2
R6_2.5.1
colorspace 2.0-2
processx_3.5.2
Biobase_2.54.0
callr 3.7.0
htmltools_0.5.2
fastmap_1.1.0
RSOLite 2.2.10
GO. db_3.13.0
munse11_0.5.0
zlibbioc 1.38.0
parallel_4.1.2
knitr 1.37
pkgload_1.2.4
png_0.1-7
cachem_1.0.6
memoise_2.0.1
randomForest4.7-1
dynamicTreeCut_1.63-1
devtools_2.4.3
bit64_4.0.5
doParallel_1.0.17
GenomeInfoDb_1.28.4
backports_1.4.1
rpart_4.1.16
Hmisc_4.6-0
net 7.3-17
withr 2.4.3
preprocessore_1.54.0 bit 4.0.4
htmlTable_2.4.0
desc_1.4.0
stringr_1.4.0
digest_0.6.29
base64enc_0.1-3
jpeg_0.1-9
htmlwidgets_1.5.4
rlang_1.0.1
generics 0.1.2
dplyr_1.0.8
GenomeInfoDbData1.2.6 Formula_1.2-4
S4Vectors 0.30.2
fansi1.0.2
brio 1.1.3
pkgbuild_1.3.1
crayon_1.5.0
lattice 0.20-45
DS_1.6.0
pillar 1.7.0
glue_1.6.1
latticeExtra_0.6-29
vetrs_0.3.8
testthat_3.1.2
xfun 0. 29
survival_3.2-13
IRanges_2.26.0
cluster_2.1.2
.

**Comment by lmbramer** [comment]
@fp215 - I think the issue is that imd_test was an internal function. You should be able to use imd_anova with similar arguments to get what you're looking for. Let me know if you're still running into issues.
