### ISSUE TITLE
dim_reduction() function needs minor fix line 76

### ISSUE THREAD

**Issue by stratkg** [pmartR/pmartR#176]
From Jan, working off the main branch:

I saw something that looked off on line 76 in pmartR’s dim_reduction.R file. The code is supposed to remove features with near zero variance, but the assignment portion of that task is missing.

Line 76:
temp_data[-minvars, ]

I think line 76 should mimic line 70 and read:
temp_data = temp_data[-minvars, ]

**Comment by evanamartin** [comment]
Resolved with pmartR version 2.0.2
