### ISSUE TITLE
check in pre-flight causing protein rollup to crash

### ISSUE THREAD

**Issue by clabornd** [pmartR/pmartR#195]
From the example in protein_quant():

```
devtools::load_all(".")
library(pmartRdata)

mypepData <- group_designation(omicsData = pep_object, main_effects = c("Condition"))
mypepData = edata_transform(mypepData, "log2")
mypepData <- applyFilt(molecule_filter(mypepData), mypepData)

results<- protein_quant(pepData = mypepData, method = 'rollup', combine_fn = 'median', isoformRes = NULL)

>  Error in pre_flight(e_data = e_data, f_data = f_data, e_meta = e_meta,  : 
  Not all e_data cname and e_meta cname combinations are unique
```

It seems that in [this chunk](https://github.com/pmartR/pmartR/blob/11c338a193655cb8e30f010c05401a4e8728f3dd/R/as.omicsData.R#L1528) we are checking to see if there are no duplicate rows in `e_meta[,c(edata_cname, emeta_cname)]`.  However this will happen during peptide rollup, since edata_cname == emeta_cname == protein column.  The protein column will have duplicates, and so we fail here.

**Comment by evanamartin** [comment]
Resolved with pmartR version 2.0.6
