### ISSUE TITLE
Extra check for pair_id + pair_group

### ISSUE THREAD

**Issue by clabornd** [pmartR/pmartR#198]
Came across this with an error in `pmartR::summary.imdanovaFilt()` from an imd_anovafilter made on a paired data object.  Turns out **I was mis-specifying the pair_group column such that certain pairs did not have two levels in pair_group**.  Still making this issue in case we want to have an extra check for user error.  

There is a check for having only 2 levels in the pair group column, but I think we also want a check for having exactly 1 entry in pair_group that == pair_denom for every pair.

I wrote up a check in [this branch](https://github.com/pmartR/pmartR/compare/bugfix/check-pair-group) if it helps explain what I mean.

**Comment by evanamartin** [comment]
This issue is taken care of with pmartR version 2.0.7.
