### ISSUE TITLE
add a thresholding option to edata_replace, so that everything below a specified threshold is considered NA

### ISSUE THREAD

**Issue by stratkg** [pmartR/pmartR#206]
From Che:

I use pmartR a lot for my GCMS data, recently I’ve started using it for LCMS data as well, however I see one issue. We can use “0” to denote missing values, but in addition to that, can we use a threshold. Say anything less than 1e5 is considered missing? The reason for this is that many programs we use to process LCMS data will never put something as 0 (there is always something), but if it is less than some threshold, we know it is ‘missing’ or ‘not detected’. This is the same for HiRes GC data.

**Comment by clabornd** [comment]
See #306
