### ISSUE TITLE
emeta_cname shows up in object

### ISSUE THREAD

**Issue by clabornd** [pmartR/pmartR#241]
I think this is a consequence of a purrr::list_modify change in 1.0.0 https://github.com/tidyverse/purrr/releases/tag/v1.0.0.  

Basically, the call Evan M had in as.xxData _did_ work when:

```
mylist = list("a" = 1, "b" = 2)
purrr::list_modify(mylist, "b" = NULL)
```

returned

`list("a" = 1)`

but now it returns

`list("a" = 1, "b" = NULL)`

Will think about how to fix, but in the meantime see if your purrr version is >= 1.0.0 and downgrade if so.

**Comment by lmbramer** [comment]
I don't see a reason to explicitly return the list item is NULL

**Comment by clabornd** [comment]
Yea it's a bit odd, there's a catch in `pre_flight` for the scenario where a user inputs an `emeta_cname` but no `e_meta`.  `pre_flight` checks for this and returns a 'new' `e_meta_cname` (NULL) to replace whatever the user entered, and throws a warning. 

https://github.com/pmartR/pmartR/blob/50f1e02f5d1ded5b99f3aea2e0034fae57bf8d89/R/as.omicsData.R#L1492

I think this is...mostly fine?  I was gonna just change the `list_modify` calls to brackets.

**Comment by clabornd** [comment]
#246
