### ISSUE TITLE
Error in nonmissing_per_group count assignment when edata and fdata sample ordering differs

### ISSUE THREAD

**Issue by javenrflo** [pmartR/pmartR#253]
When the samples (columns) of e_data are not consistent in ordering with the sample ordering in f_data, group labels may be incorrectly assigned to counts computed by nonmissing_per_group. Please refer to the reproducible example below for reference.

edat <-  data.frame(PepID = c("A", "B"), group1_time1 = c(NA, 11), group2_time1 = c(22, NA), group1_time2 = c(33, NA), group2_time2 = c(44, NA))

emeta <- data.frame(PepID = c("A", "B"), Protein = c("PA", "PB"), Peptide = c("pA", "pB"))

fdat <- data.frame(SampleID = c("group1_time2",  "group1_time1",  "group2_time2",  "group2_time1"),
                      sGroup = c("G1", "G1", "G2", "G2"),
                      sTime = c("T2", "T1", "T2", "T1"))

pmdat <- as.pepData(e_data = edat, f_data = fdat, e_meta = emeta,
                       edata_cname = "PepID", emeta_cname = "Protein", fdata_cname = "SampleID",
                       data_scale = "abundance")
pmdat <- group_designation(pmdat, main_effects = c("sGroup", "sTime"))

nonmissing_per_group(pmdat)

**Comment by clabornd** [comment]
Yea it looks like `order()` was being called on the wrong vector(s).  See https://github.com/pmartR/pmartR/commit/3005e49281ff4c9877da0f7015f8804e1f699d9b

I think there may be similar issues in places that call kw_rcpp:
https://github.com/pmartR/pmartR/blob/cee873908df744c09af4332b2b9e80cd010665f3/R/subset_funcs.R#L195

**Comment by clabornd** [comment]
Nvm, my edit breaks the cpp group size function, Evan is looking into it.
