### ISSUE TITLE
combine_lipids errors our when duplicate e_meta names are present

### ISSUE THREAD

**Issue by clabornd** [pmartR/pmartR#256]
If there are two objects with e_meta columns "A", "B", "C", with emeta_cname's "A" and "C" respectively, the second object will attempt to rename the "C" column to "A" in order to do a dplyr::bind_rows, but this fails because theres already an "A" column.

An example (ask Daniel or Kelly for this data):

```
edata <- read_csv("~/Documents/Data/example_omicsdata/lipids-error-testing/lipid_neg_edata_no_dups.csv")
fdata <- read("~/Documents/Data/example_omicsdata/lipids-error-testing/lipid_neg_fdata.csv")
emeta <- read_csv("~/Documents/Data/example_omicsdata/lipids-error-testing/lipid_neg_emeta.csv")

myobj <- as.lipidData(edata, fdata, emeta, edata_cname = "Lipid_NoDups", fdata_cname = "SampleID", emeta_cname = "Lipid")

edata2 <- read_csv("~/Documents/Data/example_omicsdata/lipids-error-testing/lipid_pos_edata_no_dups.csv")
emeta2 <- read_csv("~/Documents/Data/example_omicsdata/lipids-error-testing/lipid_pos_emeta.csv")

myobj2 <- as.lipidData(edata2, fdata, emeta2, edata_cname = "Lipid_NoDups", fdata_cname = "SampleID", emeta_cname = "Lipid_NoDups")

myobj <- group_designation(myobj, "Virus")
myobj2 <- group_designation(myobj2, "Virus")

combine_lipidData(myobj, myobj2)
```

**Comment by evanglass** [comment]
Could this also be a problem in combine_lipidData.R:111-121?
```R
## Create the combined e_data
  
  # we will use the e_data cname from the first object, we did not require that
  # they both have the same e_data_cname.
  new_edata_cname = get_edata_cname(obj_1)
  
  # bind the two data frames
  new_edata <- dplyr::bind_rows(
    obj_1$e_data, 
    obj_2$e_data %>% 
      dplyr::rename(setNames(
        get_edata_cname(obj_2), 
        get_edata_cname(obj_1)
      ))
  )
```

**Comment by clabornd** [comment]
Ah, yes...much less likely but it is technically possible

**Comment by evanglass** [comment]
It looks like there is no real solution to this besides changing the column names in the emeta file. 
![image](https://github.com/pmartR/pmartR/assets/121138977/ecd6d781-db50-4bfa-9e11-06c62248f122)

The "Lipid" column of obj_1 would have to be identical to the "Lipid_NoDups" column (or vice versa) for them to merge correctly, otherwise you'll have a mismatch between the edata cname column and the emeta cname column values, which is what that part of pre_flight was catching.
