### ISSUE TITLE
minor vignette updates 

### ISSUE THREAD

**Issue by stratkg** [pmartR/pmartR#259]
In the "Typical_Processing_Workflow" vignette, update the code chunk starting on line 410 (tag is "spans_normalize") so that it reflects this screen shot. Currently this code chunk is identical to the one above it, and we need to actually apply the normalization to the pepData object "mypep".

![image](https://user-images.githubusercontent.com/18033983/232864834-e566b2d5-1c02-48be-a165-982c1b1ab057.png)

In the "Filter_Functionality" vignette, add an example of using the imdanova_filter() function with the "comparisons" argument specifying some custom comparisons (and not just the default of all pairwise). Recommend adding this example right before the ### Custom Filter section. Can use the following text and code chunk:

By default, the IMD-ANOVA filter assumes that all pairwise comparisons will be performed in downstream use of the imd_anova() function. A user can specify custom comparisons using the "comparisons" argument when they apply the IMD-ANOVA filter. For instance if the comparisons of interest are Phenotype2 versus Phenotype1 and Phenotype3 versus Phenotype1, the following code can be used.

```{r specify comparisons}
mypep_imdanovafilt <- applyFilt(filter_object = myimdanovafilt, omicsData = mypep_groups_log2, min_nonmiss_anova = 2, min_nonmiss_gtest = 3, comparisons = data.frame(Control = c("Phenotype1", "Phenotype1"), Test = c("Phenotype2", "Phenotype3")))
```

**Comment by evanglass** [comment]
Done, see linked PR.
