### ISSUE TITLE
Possible memory issue with imd_anova()

### ISSUE THREAD

**Issue by stratkg** [pmartR/pmartR#260]
Or maybe it's not this function and it's something with the dataset that we're using or the non-pmartR code that's run prior to imd_anova(), because so far we only see the following error with one particular dataset.

Please contact Kelly Stratton and Damon Leach for the specific code and data files that result in this error:

“GC encountered a node (0x7fcb0502ba88) with an unknown SEXP type: 29 at memory.c:1817”

**Comment by clabornd** [comment]
@stratkg if you can send that code/data to @evanglass he can take a look.

**Comment by clabornd** [comment]
#263
