### ISSUE TITLE
Error in fold change computation when control group name is a substring of the test group name

### ISSUE THREAD

**Issue by javenrflo** [pmartR/pmartR#262]
Please see the reproducible example below for a demonstration of the issue: 

temp_edata <- pmartRdata::pep_edata
colnames(temp_edata) <- gsub("B", "AB", colnames(temp_edata))

temp_fdata <- pmartRdata::pep_fdata
temp_fdata$SampleID <- gsub("B", "AB", temp_fdata$SampleID)
temp_fdata$SecondPhenotype <- gsub("B", "AB", temp_fdata$SecondPhenotype)

all(temp_fdata$SampleID %in% colnames(temp_edata)[-1])

temp_pdat <- as.pepData(e_data = temp_edata, f_data = temp_fdata,
                        edata_cname = "Peptide", fdata_cname = "SampleID",
                        data_scale = "abundance")

temp_pdat <- edata_replace(temp_pdat, x = 0, y = NA)

temp_pdat <- edata_transform(temp_pdat, data_scale = "log2")

temp_pdat <- group_designation(temp_pdat, main_effects = c("Phenotype", "SecondPhenotype"))

temp_pdat_norm <- normalize_global(omicsData = temp_pdat,
                                   subset_fn = "all",
                                   norm_fn = "median",
                                   apply_norm = TRUE,
                                   backtransform = TRUE)

temp_gdf <- attr(temp_pdat, "group_DF") %>% 
  dplyr::select(-SampleID) %>% 
  dplyr::distinct()

temp_comps <- data.frame(Control = c(temp_gdf %>% dplyr::filter(Phenotype == "Phenotype3", SecondPhenotype == "A") %>% .$Group),
                         Test    = c(temp_gdf %>% dplyr::filter(Phenotype == "Phenotype3", SecondPhenotype == "AB") %>% .$Group))

temp_res <- imd_anova(omicsData = temp_pdat_norm, comparisons = temp_comps, test_method = "anova", 
                        pval_adjust_a = "none", pval_adjust_g = "none", pval_thresh = 0.05)

all.equal(temp_res$Mean_Phenotype3_AB - temp_res$Mean_Phenotype3_A, 
          temp_res$Fold_change_Phenotype3_AB_vs_Phenotype3_A)
head(temp_res$Mean_Phenotype3_AB - temp_res$Mean_Phenotype3_A)
head(temp_res$Fold_change_Phenotype3_AB_vs_Phenotype3_A)

**Comment by evanglass** [comment]
Looks like this is fixed on develop.

**Comment by clabornd** [comment]
Yea sorry we missed this, we're going back through some old issues.  Just for record keeping, I think this was pretty much the same as #254 which was fixed by https://github.com/pmartR/pmartR/pull/255
