### ISSUE TITLE
More options for plot.naRes

### ISSUE THREAD

**Issue by clabornd** [pmartR/pmartR#266]
1. 
the missing values plot function: 
https://github.com/pmartR/pmartR/blob/cee873908df744c09af4332b2b9e80cd010665f3/R/plot_fns.R#L1046

Has an option for ordering and coloring by a value in f_data.  However we also want to be able to color/order by the group assignment in group_DF (`attr(object, 'group_DF')$Group`).

2.
We also want the option for the bar heights to be:  
- the number of NON-missing values as well as missing values
- the _proportion_ of missing/non-missing values

**Comment by clabornd** [comment]
@evanglass found one thing while testing the pca plots in the app and trying to select a numeric column:

```
Warning: Error in : Continuous value supplied to discrete scale
```

I think we just need to convert certain values in the plotting dataframe to characters/factors, similar to how it's done in `plot.naRes`:  https://github.com/pmartR/pmartR/blob/e9a85669c711a679434f958dbaf356b839754ba8/R/plot_fns.R#L1202

Can you take a look?

**Comment by evanglass** [comment]
I pushed a commit to the existing branch which should fix it.

**Comment by clabornd** [comment]
see #268 and #271
