### ISSUE TITLE
plot.omicsData plot title incorrect with pre-normalized object

### ISSUE THREAD

**Issue by lmbramer** [pmartR/pmartR#275]
I created an object specifying that data was already normalized like so:

`infec_lip = as.lipidData(e_data = infec_edata, f_data = infec_fdata, e_meta = infec_emeta, edata_cname = "Lipid", fdata_cname = "SampleID", emeta_cname = "Class", data_scale = "log2", is_normalized = TRUE)`

When calling plot() on the lipidData object, the title reads "Boxplots of Reference Standardized Normalized Lipid Data" when I did not specify that any Reference Standardization had happened. In this case, I would expect it to read "Boxplots of Normalized Lipid Data"

**Comment by evanglass** [comment]
I'm not sure why it didn't auto-close this when the pull request was merged, but this is fixed now.
