### ISSUE TITLE
suggestion to replace vignettes: articles

### ISSUE THREAD

**Issue by maelle** [pmartR/pmartR#296]
https://r-pkgs.org/vignettes.html#sec-vignettes-article :smile_cat:

**Comment by clabornd** [comment]
Thanks for the suggestion, this is probably better than our current solution of just not shipping the vignettes and publishing them only on github pages.  I think in the future we'll include some of the lighter-weight vignettes and keep the rest as articles, as our primary reason for not shipping them was that they seriously inflated the package size.
