### ISSUE TITLE
Easy Fix: Volcano plot mislabeling points

### ISSUE THREAD

**Issue by javenrflo** [pmartR/pmartR#304]
line 6518 of plot_fns.R should be "volcano$Comparison". (see below)

volcano <-
    merge(merge(fc_data, pvals, all = TRUE), fc_flags, all = TRUE)

  # levels of comparison now of the form 'GROUPNAME_X vs GROUPNAME_Y'
  volcano$Comparison <-
    gsub(
      pattern = "_vs_",
      replacement = " vs ",
      pvals$Comparison # this is the part that should be changed to volcano$Comparison
    )

Current implementation has resulted in misaligned "Comparison" labels for some datasets.

**Comment by clabornd** [comment]
#305
