### ISSUE TITLE
G-test heatmap sometimes fails to mark significant cells 

### ISSUE THREAD

**Issue by javenrflo** [pmartR/pmartR#312]
In working with a specific dataset, I found that there were statistically significant results for 2 vs 0 (or vice-versa) non-missing count comparisons, yet the corresponding G-test heatmap did not mark the appropriate cells with a white dot to denote significance. 

Upon further review, I found that the reason for this was that not all 2 vs 0 comparisons were significant so that in line 6790 of R/plot_funs.R:

dplyr::summarise(n = dplyr::n(), sig = **all(P_value < 0.05)**)

the "sig" argument evaluated to FALSE. 

Normally, one should expect all comparisons of the same count sets (e.g. 2 vs 0 or 0 vs 2) to have identical p-values. This is true when considering unadjusted p-values. However, when obtaining adjusted p-values, this is not necessarily guaranteed. 

A simple but incomplete fix would be to change line 6790 of R/plot_funs.R to instead read:

dplyr::summarise(n = dplyr::n(), sig = **any(P_value < 0.05)**)

However, the counts presented in the g-test heatmap cells may then be mistakenly interpreted as the number of significant comparisons for that cell. Maybe, for the significant cells, an additional count enclosed in parentheticals could be displayed indicating the number of significant?

**Comment by clabornd** [comment]
Ah yes good catch - this is being caused by the multiple comparisons (per-biomolecule) p-value adjustment right?  FDR (across all biomolecules) adjustment should be fine here if I understand correctly.  

I think your proposed solution is good:  `any()` + add plot text for number significant.  I'll probably hand this to evan to get something whipped up unless you had something already.

**Comment by clabornd** [comment]
@javenrflo when you have time can you try out my changes in #314 with your data that results in this behavior?  I can test as well if you're able to share the data.

**Comment by clabornd** [comment]
Okay I believe I fixed the other issue with missing text on some of the times.  Was the classic NA's messing with sum().

**Comment by clabornd** [comment]
#314
