### ISSUE TITLE
IMD-Anova filter does not carry through protein roll-up, which sometimes prevents protein-level analyses using imd_anova

### ISSUE THREAD

**Issue by javenrflo** [pmartR/pmartR#313]
For global proteomics data, my usual workflow involves applying an imd-anova filter prior to filtering the data for outliers. 

This considered, there have been instances where an analytic group of interest with only three replicates is found to contain an outlier that is subsequently removed, resulting in the group having only two replicates. When the peptide-level data are then rolled-up to the protein-level and subsequently analyzed using the imd_anova function, the following error is output and no analyses are completed:

Error in applyFilt.imdanovaFilt(filta, omicsData = omicsData, min_nonmiss_anova = 2,  : 
  min_nonmiss_gtest cannot be greater than the minimum group size

This error is triggered owing to the fact that post-rollup, the imd_anova attribute is lost (i.e not carried through), which then causes the code within the if statement beginning on line 157 of R/imd_anova.R to execute. Then, within that newly executed code, values for min_nonmiss_anova and min_nonmiss_gtest are hardcoded to 2 and 3, respectively. In the specific case where we have a group with 2 replicates, this then yields the above posted error since the hardcoded value of 3 is greater than the min group size of 2.

**Comment by clabornd** [comment]
Hmmm yea so I guess we can do:
- Carry over the imd-anova filter after rollup
- Remove the auto-imd-anova-filter or make it optional for imd_anova

Not sure if this is handled already but I think in either case we'll need to change imd_anova to auto-ignore comparisons without enough samples?  I'll take a look at what the output of imd_anova looks like if I just hack past the auto-filter.

@lmbramer @stratkg any thoughts?

**Comment by clabornd** [comment]
Okay I think I was overthinking this....I've simply removed the section of imd_anova where it runs `imdanova_filter` and `applyFilt`.  All this chunk was doing was getting which/how many biomolecules would be filtered if you did apply it, in order to add this information to a warning.  I've just chopped this down to a less informative warning, which I think makes the code simpler/more robust and doesn't really lose much.

#319
