### ISSUE TITLE
On the off chance someone doesn't filter -- non-explicit error for protein_quant

### ISSUE THREAD

**Issue by rarichardson92** [pmartR/pmartR#315]
protein_quant will error "row names supplied are of the wrong length" if someone passes biomolecules that have zero observations

**Comment by rarichardson92** [comment]
Possible fix: Could add a line to run something like

"omicsData <- applyFilt(molecule_filter(omicsData), omicsData, min_num = 1)" 

right before returning the object for the as.XX functions, throwing a warning for removed biomolecules

**Comment by clabornd** [comment]
Yea that solution seems good.  I'm more a fan of just a warning about empty biomolecules, but I guess this aligns with how were handling imd_anova with the auto-application of imdanova_filter.

**Comment by clabornd** [comment]
So actually I was mistaken: imd_anova doesn't auto filter biomolecules, it just _checks_ if imdanova_filter was applied and if not applies one just to get how many/which biomolecules were removed to throw an informative warning (changed in last release).

I opted for just a more informative warning message for imd_anova, would it make sense to just have a more informative warning for protein quant?  e.g. "Your data contains <n> biomolecules with no non-missing values:  <list>, please apply a molecule filter to remove these biomolecules before protein_quant"

**Comment by stratkg** [comment]
What about this instead of the double negative? "Your data contains biomolecules not observed in any of the samples: , please apply a molecule filter to remove these biomolecules before protein_quant"

**Comment by clabornd** [comment]
#323

Went with throwing an error.  There might be a better place to check this, like in pre_flight or at the end of pmartR_filter_worker.  Filtering maybe most logical since it's the likeliest place for this to occur....will go with this for now.

**Comment by clabornd** [comment]
Calling it fixed via #323.  We can still look into related #212, which should make it so that this only happens if someone creates all-missing observations via filtering or some other mechanism.
