### ISSUE TITLE
Allow rmd_filter to accept pre-logged and centered data

### ISSUE THREAD

**Issue by abadgerw** [pmartR/pmartR#327]
I am hoping to check for outliers after performing batch correction and the algorithm I'm using outputs a log transformed matrix that is centered at 0. When using the rmd_filter function I receive an error about the data not being log transformed by the edata_transform function. Is there any way to have the rmd_filter accept a more flexible input?

**Comment by clabornd** [comment]
If your data is log-transformed and centered before using pmartR, you can specify `data_scale='log2'` and `is_normalized = TRUE` when creating your object using `as.xxxData`.  This should allow it to pass through the rMd filter.
