### ISSUE TITLE
proteomics filter can't handle redundancy with non-standard emeta_cname

### ISSUE THREAD

**Issue by rarichardson92** [pmartR/pmartR#332]
Error on the example below, working on fix to ensure filter tables don't use checknames

```
library(pmartR)
library(pmartRdata)

e_data <- pmartRdata::pep_edata
edata_cname <- "Peptide"

f_data <- pmartRdata::pep_fdata
fdata_cname <- "SampleID"

e_meta <- pmartRdata::pep_emeta

## Induce redundancy
pep <- e_meta[1, "Peptide"]
df <- e_meta[2,]
df$Peptide <- pep
e_meta <- rbind(e_meta, df)

## Inconvenient name
e_meta[["Razor protein"]] <- e_meta$RazorProtein
emeta_cname <- "Razor protein"

pep_object <- as.pepData(
  e_data = e_data,
  f_data = f_data,
  e_meta = e_meta,
  edata_cname = edata_cname,
  fdata_cname = fdata_cname,
  emeta_cname = emeta_cname
)

my_filter <- proteomics_filter(omicsData = pep_object)
plot(my_filter, "redundancy")

applyFilt(filter_object = my_filter, omicsData = pep_object, min_num_peps = 2, redundancy = T)
```

**Comment by clabornd** [comment]
#335

**Comment by rarichardson92** [comment]
@clabornd investigating the ajax issue has presented me with a possible cleaner solution -- idk if package functions have a global equivalent, but this might do and prevent future issues:

formals(data.frame)$check.names <- FALSE

**Comment by clabornd** [comment]
Interesting, I guess my concern would be whether we could do this only inside the package, not affecting `data.frame` calls outside of pmarR when it gets loaded.  If so this could be a nice solution.  

I was also thinking about a solution _forces `check.names = TRUE`_ but just informs the user that all their columns were modified as well as any `**_cname` inputs they provided.  Would be quite ironic if we did this considering how much effort was put into `check.names = F`.
